/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false` (hash: 51b7e73553bb2f400d24bd8abfb43d12)
interface __BaseEnv_Env {
	AI: Ai;
	MODEL_MODE: string;
	MODEL_ID: string;
	IncidentAgent: DurableObjectNamespace<import("./src/server/index").IncidentAgent>;
	INVESTIGATION_WORKFLOW: Workflow<Parameters<import("./src/server/index").InvestigationWorkflow['run']>[0]['payload']>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server/index");
		durableNamespaces: "IncidentAgent";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "MODEL_MODE" | "MODEL_ID">> {}
}
declare module "*.txt" {
	const value: string;
	export default value;
}